### ISSUE TITLE
Any plan of supporting Grammar-Kit?

### ISSUE THREAD

**Issue by ice1000** [thautwarm/EBNFParser#5]
[Grammar-Kit](https://github.com/JetBrains/Grammar-Kit) is a parser generator made by JB, generates IDE-capable parser code. The parser is using a builder which holds a sequence of `Token`s, and the parser use the builder, create a structured AST.

This tool is somehow difficult to use because it provides extremely limited support for left recursions.

Any plan of superseding that?

**Comment by ice1000** [comment]
Grammar-Kit generates:

+ A parser class extending `PsiParser` and `PsiLightParser`
+ Classes representing the AST elements, you can make it extends some other classes
+ Methods to get its childs, like if I have

```
rule :: b '+' c
```

You'll see the class representing `rule` witll have a `getB` and `getC` method.

**Comment by ice1000** [comment]
`whitespace`s are ignored during token generation.

**Comment by thautwarm** [comment]
@ice1000 I thought I didn't really get what you mean to. 

I guess that you want to write Ruiko EBNF and then compile it to Grammar Kit? It seems impossible if the LR handler in Grammar Kit is limited.  

If you want to write Ruiko EBNF and use it as an alternative in developing Intellij plugins, It might be much easier, however currently there is some wrong with EBNFParser's design(the token finally becomes string but a generic type is better) so I feel reluctant to migrate this incomplete version to other platforms...  

Actually it's not a hard task to implement EBNFParser in other platforms like .NET and JVM because essentially it's only parserc with control flows, however, I don't want  to do these due to lack of time...

**Comment by ice1000** [comment]
I mean just implement another backend of EBNFParser which takes a bnf file and produce a IDE-capable parser

**Comment by ice1000** [comment]
> If you want to write Ruiko EBNF and use it as an alternative in developing Intellij plugins, It might be much easier

Yeah this is exactly what I mean

**Comment by ice1000** [comment]
> I feel reluctant to migrate this incomplete version to other platforms...

It's OK, I'm not urgent

**Comment by thautwarm** [comment]
@ice1000 I've been refactoring ebnfparser all day along... I hope I can make it today..

**Comment by ice1000** [comment]
Love you, chew :kissing_heart:
